Traceback (most recent call last):
  File "/home/dani/Code/Python/ITA/C2/W5/./streams_err.py", line 5, in <module>
    raise ValueError("Now we generate an error to STDERR")
ValueError: Now we generate an error to STDERR
